### ISSUE TITLE
Adjusting the width of custom scroll bar

### ISSUE THREAD

**Issue by TG922** [Hackathon7/Pacify-final#106]
## Description

- I want to adjust the scroll bar of the page, as it's width is too less.
- This feature will help increase User Interface(UI) of your website.

![Image5](https://user-images.githubusercontent.com/70098839/158019234-bc46364f-87c1-4eab-bf02-9c69175517b2.PNG)

**Comment by dvlsatya** [comment]
can you assign this work to me

**Comment by TG922** [comment]
> can you assign this work to me

Ok go on @dvlsatya !!

**Comment by priyanshusingh305** [comment]
Can I please work on this issue?

**Comment by TG922** [comment]
@tarunsinghofficial please assign #106 to @dvlsatya as he is interested !! I can work on another issue for ur project

**Comment by dvlsatya** [comment]
@tarunsinghofficial please assign this work to me

**Comment by Rishita489** [comment]
Hey @tarunsinghofficial  , I am GSSOC'22 contributor . 
I have improved the UI of the scrollbar and also changed the color on hovering over it . Can you please assign this issue to me so that I can send the pull request . 

![image](https://user-images.githubusercontent.com/73689669/161153596-b1ceb068-0481-4b17-8b23-910c02329b40.png)

**Comment by Rishita489** [comment]
I have also added rounded scrollbar to improve the UI .

**Comment by Rishita489** [comment]
Hey @tarunsinghofficial , I have send the pull request for this issue . Can you please review and merge it
